name: CI/CD com Docker e Testes

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm run test

      - name: Build da imagem Docker
        run: docker build -t pedromonteiro7/biox-api:latest .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Enviar imagem para o Docker Hub
        run: docker push pedromonteiro7/biox-api:latest

      - name: Acionar deploy no Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
